### ISSUE TITLE
Create an integration pipeline

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/rafter#5]
**Description**

Implement integration tests and pipelines for whole Rafter. Execute tests on Kind.

> Be careful with credentials in Gateway modes.

AC:
 - Reuse integration tests we have on Kyma
 - Tests are working in and outside the cluster
 - For CI Kind is used
 - Gateway modes are also tested
 - Make sure we generate JUnit reports

**Reasons**

Automated validation if Rafter works.

**Related issue(s)**
kyma-project/kyma#5585

**Comment by aerfio** [comment]
See https://github.com/kyma-project/rafter/issues/19#issuecomment-557100267 as a comment about JUnit reports

**Comment by derberg** [comment]
To be able to accept I need a summary comment what has changed in comparison to previous pipelines we had on Kyma, or info that nothing changed and we test exactly the same way with the same flows as before

**Comment by michal-hudy** [comment]
@aerfio @magicmatatjahu @m00g3n can you guys share a details with @derberg ?

**Comment by magicmatatjahu** [comment]
@derberg MiniO Gateway mode and with Migration step testing are very similar to old pipelines. Differences:
- kind is used
- all tests (migration, gateways, integration and units) generate junit reports.
- common gateway helper scripts is copied from test-infra to this repo with small modification - only script for periodic removing StorageAccounts from Azure stay in test-infra, and also fo buckets in GCS.
- we using helpers from kind, junit etc from test-infra so we need at the moment reference to this repo in environment (locally or as extraRef in CI)
- long term we want switch from bash to go
- we can also run tests outside and inside cluster - but we need locally required envs, which are described in this PR https://github.com/kyma-project/rafter/pull/34
- also we using local charts from `charts` folder to testing in integration, gateways and migration
tests for testing changes in charts - thanks to @michal-hudy for ping of missing action item.

@aerfio I forget about something?

**Comment by aerfio** [comment]
@derberg 
- as magic said, for test we use specific kind, kubectl, helm & tiller versions, those binaries are downloaded before the test to temporary directory, which is cleaned up after the test, it works on macos and linux
- the fact that we install every needed binary ourselves means that you only have to have docker installed (and go ofc) to type `make integration-test` and it should work without any env variable, just like it does in prow
- we are expecting users to have test-infra repo cloned, as magic said, because we are using scripts from there
- the logic for tests is kept in rafter repo, not in test-infra (see whole hack/ci folder)
- I've made small [POC](https://github.com/aerfio/kindFromGoShowcase) for tests in go only in my free time, it doesn't work yet but it is certainly possible (there's an issue for that, #19)
- yeah, junits everywhere, as a stretch I've also added junit for unit tests, as it was quite easy to do so
- some changes in test-infra were also needed to make it work here
- as far as I understood we only run tests outside of cluster

**Comment by aerfio** [comment]
And as for #17 it technically should not be in the scope of this issue, but it was done because we thought that it fixes some issues with tests (initially we had quite a problem to run integration tests), but in the end it wasn't necessary

I think now it's up to @m00g3n to review, but it's not a blocker for this issue to be closed

**Comment by derberg** [comment]
@magicmatatjahu @aerfio awesome update guys, thanks a lot!

only one thing, I could not find on master any info about this dependency to `test-infra` repo, also no info is added to this PR https://github.com/kyma-project/rafter/pull/34/files. Please make sure it is part of instructions if I really need `test-infra` to be able to run tests locally. But if it is only a script for periodic cleanup of Azure, I say we do not need to have it documented

**Comment by aerfio** [comment]
@derberg https://github.com/kyma-project/rafter/pull/34/files#diff-f34afc2c1f412ffa73a5a1717ae9750dR49 it is, we payed attention to that
